#!/bin/bash
 
# Modify the shell script from exercise 1 to include 
# a variable. The variable will hold the contents
# of the message "Shell Scripting is Fun!".
MSG="Shell Scripting is Fun!"

echo "$MSG"